apiVersion: v1
kind: Service
metadata:
  name: icebarn-rs
  labels:
    app.kubernetes.io/name: icebarn-rs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: icebarn-rs
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
